name: sn_intel
'on':
  - push
  - pull_request
concurrency:
  group: sn-intel
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  intel:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
