name: sn_ledger
'on':
  - push
  - pull_request
concurrency:
  group: sn-ledger
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
